# Site wide configuration

title: 		"Nemophily Natives"
description: 	"Specializing in native plants for the southeastern USA"
logo: favicon.png # 128x128 px default image used for Twitter summary card
teaser: favicon.png # 400x250 px default teaser image used in image archive grid
locale: 	en_US
baseurl:	""
#url: https://fritchie21.github.io
url: 		https://nemophilynatives.com
feed:
  path: atom.xml

# Jekyll configuration

#permalink: /:categories/:title/
sass:
  sass_dir: _sass
  style: compressed
kramdown:
  toc_levels: 1..4
highlighter: rouge
plugins:
  - jekyll-gist
  - jekyll-feed
  - jekyll-avatar
  - jekyll-sitemap

# Site owner
owner:
  name: Matthew Wolak
  email: matthewwolak@gmail.com
  twitter:
  github: matthewwolak
  bio: "Dumb Brute Apprentice"
  avatar: bio-WolakMatthew.png # 160x160 px image for author byline
  disqus-shortname: matthewwolak

picture:
  source: images/_fullsize
  output: images


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
  
encoding: utf-8
timezone: America/Chicago  
